name: Coana Vulnerability Analysis
 
on:
  schedule:
    - cron: '0 3 * * *' # every day at 3 AM
 
jobs:
  coana-vulnerability-analysis:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
 
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
 
      - name: Install dependencies
        run: npm install
        # run: pnpm install
        # run: yarn install
 
      - name: Run Coana CLI
        id: coana-cli
        uses: coana-tech/coana-action/vulnerability-analysis@stable
        with:
          apiKey: ${{ secrets.COANA_API_TOKEN }}
          repoUrl: https://github.com/${{github.repository}}
